[default]
JWT_SECRET = ""
ALGORITHM = ""

[production]
JWT_SECRET = ""
DB_URI = "postgresql+asyncpg://postgres:Vish_123123@192.168.1.2:5432/db_exemple_development"

[development]
JWT_SECRET = ""
DB_URI = "postgresql+asyncpg://postgres:Vish_123123@192.168.1.2:5432/db_exemple_development"

[testing]
JWT_SECRET = ""
DB_URI = "postgresql+asyncpg://postgres:Vish_123123@192.168.1.2:5432/db_exemple_development"